apiVersion: v1
kind: Config
current-context: uk-xp264--b84edf3
clusters:
  - name: uk-xp264--b84edf3
    cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRQnBmaHN3SmppckNMRlNoQ05UM0h5ekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TlRFd01ESXdOalF6TUROYUZ3MHpOVEV3TURJd05qUTBNRE5hTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF1N2d3ClBMbmFSY2k4bVZXWWdSYmNveHBNN1FybTVPQ0pUYy9xYVRNaHRqVUt2TDYyYnFPWmFBQURNaDMxVjlTbmc2S1UKUkFwdzR5ODlselNsdUh1SGZySEVmVGtXT3E4dDBqb2M1eW4raFVEeTZTbE9ZVlJ5RmY5UlZMOHV2MnRFOURkZQpHUk9CTFdXRXIwbkM2VzYwYTdUUENFeVJvQzIyU3M2cDNzZVBDaVJlVWdENk11ck8yeWxPQzFGSU9JdFZ4anlkCkFWb3hJaXlwa3l0RGw0MkRINkQwczgydW91VzZ2SVpkbWxZcW44YlMrbUZ2QkYvMGlIZC92UEdaMmo5MTcrc2QKQ1BrckF5enkxd1Y0TTRtZ1JJZ3ZMVG1PRDZyemRvOHJWRkFhUktRd3luMGplcjhhUnVzekFJejFxUDNzSlkxSAo0SlpmRzBxQUFHM2V0RkExc2Z1eWk5ZEpSZFNvZ0V6QnQzYUFWRUZKcEJlWHlncTB1K1phVkY2dWQvaDFYMmlVCjhFV1BxVDN5aHgveFZOaVpQaGRpczQyMXZPRDU0Q1RSS0JsMEVwODh6UXJkV3hGR0oxODRzcE0rZkkyc0twWTMKbURNZXkyd0ZadXR5UU10M0VqSlRsWkFWRVVPc1JIcnZZV0N0ZzF5OURITXRmb29xeXpZZ0R5UWdHTTdoQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCU0RtSHkxWkM2TjhjUWp4SjdDY2djcGxqbkZoakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBSnkxYzBHZGcKVC9WTTBicExSbzUxYnVZUHZqMGFlenpKYWUweS9lMy8vVUptTmNBOCtIb2xhaFZhOXUxVE5GYzAxK1UwR1dLNQpJVUZFNWExdjVCdWlMOGJBRzhyV0JkeVJ3QkJJelRQVTdvRm9EblZuU1FOTXVYSVNUdTE0QS84NzVkK1crM0FYCnhLand6U0RHc0U0Wmp4Zy9vVnJDNDJZU3pFcW5ISkNpTGNsVWFzM1lzNWVTWjFQNEhvcTRhcjE0U05pK20xejkKVzNLb3R3Ly9PUU95dFJGcVhBc2ZrTkVMQ25rV2RONG1FWEdOVVJpZjdDTjJ4L05LQm9yU0dWa0ZtNjd1WWJqSgoxcDhHZTIwK3ZJZEdvR1d3Q2lLendLM0hiUHpVbS9FbDZLZVVzMVdIL0o1TFRZelNJU3Q1eldyZkl6amtSY1E2CkQ1OTdWN2NBQVlDL3dWWC9wdkdWeG1DR3J1aVY5QTRjTzhYNlVFaVZaUE1ubW5wUE9XVW1KV29PSklqYkFJakIKWGNkaWpHU1RtYzBDUmxIYjUxSGdYUkhNRCs0RXhyQzV0VFQ1NVF4R1l2SHZ4SzFCUDFsbDVhU1JHdHMyd1FoMAprbzN3eW4wUSt2OUhWMzRmVXZTc1doZ0NRdTdmcHl3WUVLQzBUNWdVYlNCQWRPeTA0TDkyemY3VwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.b84edf3.kyma.ondemand.com
contexts:
  - name: uk-xp264--b84edf3
    context:
      cluster: uk-xp264--b84edf3
      user: uk-xp264--b84edf3
users:
  - name: uk-xp264--b84edf3
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://anuk8cmfw.accounts.ondemand.com'
          - '--oidc-client-id=fdc2e68d-1fa3-4614-b898-9f9ac84adef6'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
