name: who has forked me

on:
  workflow_dispatch:

permissions: 
  contents: read
  id-token: write

jobs:
  who-has-forked-me:
    runs-on: ubuntu-latest
    steps:
    - "name": "who has forked me?"
      "run": |
       echo "who has forked me? ..."
       FORKS=$(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.CICD_TOKEN_FOR_TF_MODULES }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/SAP-samples/teched2025-XP264/forks)
       echo $FORKS | jq -r '.[] | "\(.owner.login)" \(.owner.html_url)"' 